[package]
name = "rustracer"
version = "0.1.0"
authors = ["Basir Doost <dm.basir@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ultraviolet = "0.8.1"
image = "0.23.14"
rand = "0.8.4"